# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_date', models.DateField()),
                ('ev_time', models.TimeField()),
                ('ev_moment', models.CharField(max_length=15)),
                ('ev_type', models.CharField(max_length=100)),
                ('ev_forecast', models.IntegerField()),
                ('ev_surprising', models.IntegerField()),
                ('ev_impression', models.IntegerField()),
                ('ev_feeling', models.CharField(max_length=150)),
                ('ev_feelingValue', models.CharField(max_length=100)),
                ('ev_angle', models.CharField(max_length=100)),
                ('ev_description', models.TextField()),
                ('ev_img', models.ImageField(upload_to='')),
                ('ev_sound', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createevent.Trip'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='mapWrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createevent.Map'),
        ),
    ]
