# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 08:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField(blank=True, null=True)),
                ('eventMoment', models.CharField(max_length=15)),
                ('eventType', models.CharField(max_length=100)),
                ('eventForecast', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('eventSurprising', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('eventImpression', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('eventImportance', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feeling', models.CharField(max_length=150)),
                ('feelingValue', models.CharField(max_length=100)),
                ('angle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('sound', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='trip_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createevent.Trip'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='mapWrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createevent.Map'),
        ),
    ]
