# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='ev_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_forecast',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_impression',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_sound',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_surprising',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_time',
            field=models.TimeField(blank=True),
        ),
    ]
