# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0002_auto_20170918_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='ev_forecast',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_impression',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ev_surprising',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
