# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0003_auto_20170920_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_angle',
            new_name='angle',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_date',
            new_name='eventDate',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_forecast',
            new_name='eventForecast',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_impression',
            new_name='eventImpression',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_moment',
            new_name='eventMoment',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_surprising',
            new_name='eventSurprising',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_time',
            new_name='eventTime',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_feelingValue',
            new_name='eventType',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_feeling',
            new_name='feeling',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_type',
            new_name='feelingValue',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='ev_sound',
            new_name='sound',
        ),
    ]
