# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0005_auto_20170920_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='sound',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
