# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0006_auto_20170921_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='trip',
            new_name='trip_name',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tr_name',
            new_name='trip_name',
        ),
    ]
