# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0007_auto_20170921_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='trip_name',
        ),
    ]
