# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0008_remove_map_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='mapWrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createevent.Map'),
        ),
    ]
